services:
  - type: web
    name: jira-web-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /
    autoDeploy: true 